export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_SEARCH_PENDDING = 'REQUEST_SEARCH_PENDDING';
export const REQUEST_SEARCH_SUCCESS = 'REQUEST_SEARCH_SUCCESS';
export const REQUEST_SEARCH_FAILED = 'REQUEST_SEARCH_FAILED';
